### PR TITLE
Use file store from file instead from file system

### LINKED ISSUE #518: The way getFileStores() is used poses problems in a containerized application
I don't understand why the following doesn't use `Files.getFileStore(this.file.toPath())`. This retrieves the overlay correctly but the current implementation doesn't, which prevents the creation of a persisted chronicle map.

https://github.com/OpenHFT/Chronicle-Map/blob/79e6e29ebe15a7a72302310738298ac8fabec840/src/main/java/net/openhft/chronicle/hash/impl/VanillaChronicleHash.java#L1100-L1113

### PR DESCRIPTION
**Pull request by Sax388**
Resolves #518 

I tested it with the current Java 21 (`eclipse-temurin`)
```java
[WARNING] Tests run: 1291, Failures: 0, Errors: 0, Skipped: 73
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:06 min
[INFO] Finished at: 2024-02-22T21:37:48+01:00
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by JerryShea** [comment]
Thanks @Sax388 let us review.

For us to be able to merge this we will need you to sign the [CLA](https://chronicle.software/contributor-agreement/) please.

**Comment by JerryShea** [comment]
@peter-lawrey @nicktindall - I have confirmed `mvn install` passes on on of the dev servers

**Review by JerryShea — APPROVED** [review]

**Comment by Sax388** [comment]
> Thanks @Sax388 let us review.
> 
> For us to be able to merge this we will need you to sign the [CLA](https://chronicle.software/contributor-agreement/) please.

That's done ✅. Thank you for the review, I appreaciate it.

**Comment by WeatherGod** [comment]
This might actually fix my issue #530. If you can give me guidance on how to build the patched jar file, I can test it out on my system.

**Comment by Sax388** [comment]
> This might actually fix my issue #530. If you can give me guidance on how to build the patched jar file, I can test it out on my system.

You don't need to build it yourself, these changes are included in the most current version: https://mvnrepository.com/artifact/net.openhft/chronicle-map/3.25ea6

PS For building the patched jar I had to enable the maven central repository in the build file and disable the private repositories.

**Comment by WeatherGod** [comment]
Thanks, that helped, but seems like it wasn't the complete solution to the build problem. Since I'm just trying to verify the fix for a tiny piece of another project that I was using, I needed to build the 3.23.5 jar, but it seems that it's POM file points to a different chronicle-bom (2.23.123) than what the other project explicitly set in its POM (2.23.136). With chronicle-map's checkout of v3.23.5 code, I changed its POM to point to chronicle-bom:2.23.136, and it was able to build! I applied this change and am running the tests now to see how it goes.

**Comment by WeatherGod** [comment]
Confirmed! This fix solved the problem of using Chronicle-Map on a file in a k8s ephemeral volume! Thank you.

**Pull request merged**
